#include "test.h"

#include <stdio.h>
#include <stdlib.h>

const static char *tests[] = {
    "argv",
    "basename",
    "clocale_mbfuncs",
    "clock_gettime",
    "dirname",
    "env",
    "fdopen",
    "fnmatch",
    "fscanf",
    "fwscanf",
    "iconv_open",
    "inet_pton",
    "mbc",
    "memstream",
    "pthread_cancel_points",
    "pthread_cancel",
    "pthread_cond",
    "pthread_tsd",
    "qsort",
    "random",
    "search_hsearch",
    "search_insque",
    "search_lsearch",
    "search_tsearch",
    "setjmp",
    "snprintf",
    "socket",
    "sscanf",
    "sscanf_long",
    "stat",
    "strftime",
    "string",
    "string_memcpy",
    "string_memmem",
    "string_memset",
    "string_strchr",
    "string_strcspn",
    "string_strstr",
    "strptime",
    "strtod",
    "strtod_simple",
    "strtof",
    "strtol",
    "strtold",
    "swprintf",
    "tgmath",
    "time",
    "tls_align",
    "udiv",
    "ungetc",
    "utime",
    "wcsstr",
    "wcstol",
    "daemon_failure",
    "dn_expand_empty",
    "dn_expand_ptr_0",
    "fflush_exit",
    "fgets_eof",
    "fgetwc_buffering",
    "fpclassify_invalid_ld80",
    "ftello_unflushed_append",
    "getpwnam_r_crash",
    "getpwnam_r_errno",
    "iconv_roundtrips",
    "inet_ntop_v4mapped",
    "inet_pton_empty_last_field",
    "iswspace_null",
    "lrand48_signextend",
    "lseek_large",
    "malloc_0",
    "mbsrtowcs_overflow",
    "memmem_oob_read",
    "memmem_oob",
    "mkdtemp_failure",
    "mkstemp_failure",
    "printf_1e9_oob",
    "printf_fmt_g_round",
    "printf_fmt_g_zeros",
    "printf_fmt_n",
    "pthread_robust_detach",
    "pthread_cancel_sem_wait",
    "pthread_cond_smasher",
    "pthread_condattr_setclock",
    "pthread_exit_cancel",
    "pthread_once_deadlock",
    "pthread_rwlock_ebusy",
    "putenv_doublefree",
    "regex_backref_0",
    "regex_bracket_icase",
    "regex_ere_backref",
    "regex_escaped_high_byte",
    "regex_negated_range",
    "regexec_nosub",
    "rewind_clear_error",
    "rlimit_open_files",
    "scanf_bytes_consumed",
    "scanf_match_literal_eof",
    "scanf_nullbyte_char",
    "setvbuf_unget",
    "sigprocmask_internal",
    "sscanf_eof",
    "statvfs",
    "strverscmp",
    "syscall_sign_extend",
    "uselocale_0",
    "wcsncpy_read_overflow",
    "wcsstr_false_negative",
};


void test_musl_libc() {
    puts("#### OS COMP TEST GROUP START libctest-musl ####");
    for (int i = 0; i < sizeof(tests) / sizeof(tests[0]); i++) {
        run_test((char *const[]){"/musl/runtest.exe", "-w", "entry-static.exe", tests[i], NULL});
    }
    run_test((char *const[]){"/musl/entry-static.exe", NULL});
    for (int i = 0; i < sizeof(tests) / sizeof(tests[0]); i++) {
        run_test((char *const[]){"/musl/runtest.exe", "-w", "entry-dynamic.exe", tests[i], NULL});
    }
    run_test((char *const[]){"/musl/runtest.exe", "-w", "entry-dynamic.exe", "tls_get_new_dtv", NULL});
    run_test((char *const[]){"/musl/runtest.exe", "-w", "entry-dynamic.exe", "uselocale_0", NULL});
    puts("#### OS COMP TEST GROUP END libctest-musl ####");
}
